name: Run Trading Bot

on:
  workflow_dispatch:      # Tylko ręczne uruchomienie
  push:                  # I przy push

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: pip install -r requirements.txt
    - run: python trading_bot.py
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
